### ISSUE TITLE
ImportError: No Module named '_PyMesh'

### ISSUE THREAD

**Issue by punpongsanon** [qnzhou/PyMesh#10]
I managed to build and installed PyMesh in Windows and with Python 3.4. After build and install I tried to  test with  'python -c "import pymesh; pymesh.test()" as described in the manual (readme.md). 

However, I got this error;

> Traceback (most recent call last):
>   File "C:\Python\3_4\lib\site-packages\pymesh-0.1-py3.4.egg\pymesh\swig\PyMesh.py", line 18, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Python\3_4\lib\importlib\__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
> ImportError: No module named '_PyMesh'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Python\3_4\lib\site-packages\pymesh-0.1-py3.4.egg\pymesh\__init__.py", line 18, in <module>
>     from .Mesh import Mesh
>   File "C:\Python\3_4\lib\site-packages\pymesh-0.1-py3.4.egg\pymesh\Mesh.py", line 5, in <module>
>     import PyMesh
>   File "C:\Python\3_4\lib\site-packages\pymesh-0.1-py3.4.egg\pymesh\swig\PyMesh.py", line 21, in <module>
>     _PyMesh = swig_import_helper()
>   File "C:\Python\3_4\lib\site-packages\pymesh-0.1-py3.4.egg\pymesh\swig\PyMesh.py", line 20, in swig_import_helper
>     return importlib.import_module('_PyMesh')
>   File "C:\Python\3_4\lib\importlib\__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: No module named '_PyMesh'

Could you please help, did I do something wrong during installation? (no error during build and install excepted only some unnecessary library).

**Comment by qnzhou** [comment]
Could you check if the file `_PyMesh.so` or `_PyMesh.dll` is present in `C:\Python\3_4\lib\site-packages\pymesh-0.1-py3.4.egg\pymesh\lib`?

**Comment by punpongsanon** [comment]
OK, I managed it work in Ubuntu. I found some difficult to install in Windows (maybe because of my skill). The problem that I found is the src_test does not build correctly and `_PyMesh.dll` does not copy to the correct location. 

It is very comfortable when I use Ubuntu ...

**Comment by whhamber** [comment]
conda install -c conda-forge pymesh2
It is so simple and useful...

**Comment by GiantRoot** [comment]
Duplicate of #141 

I didn't try but I think this is the solution. https://github.com/PyMesh/PyMesh/issues/141#issuecomment-461423571
