### ISSUE TITLE
CMake Error at cmake/FindEigen.cmake:44 (TARGET_INCLUDE_DIRECTORIES)

### ISSUE THREAD

**Issue by ujikol** [qnzhou/PyMesh#101]
Ubuntu 18.04
`export EIGEN_INC=/usr/include/eigen3; ./setup.py build`
`CMake Error at cmake/FindEigen.cmake:44 (TARGET_INCLUDE_DIRECTORIES):
  Cannot specify include directories for imported target "PyMesh::Eigen".
Call Stack (most recent call first):
  cmake/FindAllDependencies.cmake:5 (FIND_PACKAGE)
  Settings.cmake:14 (FIND_PACKAGE)
  CMakeLists.txt:5 (INCLUDE)

CMake Error at cmake/FindEigen.cmake:49 (TARGET_COMPILE_DEFINITIONS):
  Cannot specify compile definitions for imported target "PyMesh::Eigen".
Call Stack (most recent call first):
  cmake/FindAllDependencies.cmake:5 (FIND_PACKAGE)
  Settings.cmake:14 (FIND_PACKAGE)
  CMakeLists.txt:5 (INCLUDE)

-- SparseHash not found, consider set $SPARSEHASH_PATH environment variable (missing: SPARSEHASH_INCLUDE_DIRS)
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
CMake Error at cmake/FindGMP.cmake:23 (TARGET_INCLUDE_DIRECTORIES):
  Cannot specify include directories for imported target "PyMesh::Gmp".
Call Stack (most recent call first):
  cmake/FindAllDependencies.cmake:27 (FIND_PACKAGE)
  Settings.cmake:14 (FIND_PACKAGE)
  CMakeLists.txt:5 (INCLUDE)

CMake Error at cmake/FindGMP.cmake:27 (TARGET_LINK_LIBRARIES):
  Cannot specify link libraries for target "PyMesh::Gmp" which is not built
  by this project.
Call Stack (most recent call first):
  cmake/FindAllDependencies.cmake:27 (FIND_PACKAGE)
  Settings.cmake:14 (FIND_PACKAGE)
  CMakeLists.txt:5 (INCLUDE)`

`Traceback (most recent call last):
  File "./setup.py", line 177, in <module>
    distclass=BinaryDistribution,
  File "/home/mick/dev/.virtualenvs/DLO/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "./setup.py", line 87, in run
    self.build_pymesh();
  File "./setup.py", line 80, in build_pymesh
    check_call(command.split());
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '..', '-DPythonLibsNew_FIND_VERSION=3.6.5']' returned non-zero exit status 1.`

Same problem when trying with cmake and make.

**Comment by qnzhou** [comment]
Maybe your cmake is not up-to-date?  What version is your cmake?  Here is mine:

```
$ cmake --version
cmake version 3.11.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by ujikol** [comment]
You are right. That was the cause. Ubuntu 18.04 just has cmake 3.10.x.

Could complete build and install with 3.11.4. But now got a traceback when importing pymesh:

`Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mick/dev/PyMesh/python/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/home/mick/dev/PyMesh/python/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: /home/mick/dev/PyMesh/python/pymesh/lib/libPyMesh-Boolean.so: undefined symbol: _Z17computeDifference11CorkTriMeshS_PS_`

Going to create a separate thread.
