### ISSUE TITLE
import problem: libPyMesh-Boolean.so: undefined symbol: _Z17computeDifference11CorkTriMeshS_PS_

### ISSUE THREAD

**Issue by ujikol** [qnzhou/PyMesh#104]
Ubuntu 18.4
cmake 3.11.4
built with setup build and setup install based on include third_party

`Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mick/dev/PyMesh/python/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/home/mick/dev/PyMesh/python/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: /home/mick/dev/PyMesh/python/pymesh/lib/libPyMesh-Boolean.so: undefined symbol: _Z17computeDifference11CorkTriMeshS_PS_`

**Comment by ujikol** [comment]
I tried again cmake & make third_party and pymesh -> no errors.

But make tests:
`[ 69%] Built target lib_Boolean
Scanning dependencies of target Boolean_tests
[ 70%] Building CXX object tests/tools/Boolean/CMakeFiles/Boolean_tests.dir/unit_test_driver.cpp.o
[ 70%] Linking CXX executable ../../../../bin/Boolean_tests
../../../../python/pymesh/lib/libPyMesh-Boolean.so: undefined reference to `computeDifference(CorkTriMesh, CorkTriMesh, CorkTriMesh*)'
../../../../python/pymesh/lib/libPyMesh-Boolean.so: undefined reference to `computeIntersection(CorkTriMesh, CorkTriMesh, CorkTriMesh*)'
../../../../python/pymesh/lib/libPyMesh-Boolean.so: undefined reference to `computeSymmetricDifference(CorkTriMesh, CorkTriMesh, CorkTriMesh*)'
../../../../python/pymesh/lib/libPyMesh-Boolean.so: undefined reference to `freeCorkTriMesh(CorkTriMesh*)'
../../../../python/pymesh/lib/libPyMesh-Boolean.so: undefined reference to `computeUnion(CorkTriMesh, CorkTriMesh, CorkTriMesh*)'
collect2: error: ld returned 1 exit status
tests/tools/Boolean/CMakeFiles/Boolean_tests.dir/build.make:87: recipe for target '../bin/Boolean_tests' failed
make[3]: *** [../bin/Boolean_tests] Error 1
CMakeFiles/Makefile2:3312: recipe for target 'tests/tools/Boolean/CMakeFiles/Boolean_tests.dir/all' failed
make[2]: *** [tests/tools/Boolean/CMakeFiles/Boolean_tests.dir/all] Error 2
CMakeFiles/Makefile2:2337: recipe for target 'tests/CMakeFiles/tests.dir/rule' failed
make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
Makefile:430: recipe for target 'tests' failed
make: *** [tests] Error 2`

**Comment by qnzhou** [comment]
This is pretty strange.  It seems cork is not compiled/installed correctly.  Can you run `grep -i cork CMakeCache.txt` in your build directory to see if cork is setup correctly by cmake?

**Comment by ujikol** [comment]
#grep -i cork build/CMakeCache.txt
CORK_INCLUDE_DIRS:PATH=/home/mick/dev/PyMesh/python/pymesh/third_party/include
CORK_LIBRARIES:FILEPATH=/usr/lib/x86_64-linux-gnu/libcork.so
//ADVANCED property for variable: CORK_INCLUDE_DIRS
CORK_INCLUDE_DIRS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CORK_LIBRARIES
CORK_LIBRARIES-ADVANCED:INTERNAL=1
//Details about finding Cork
FIND_PACKAGE_MESSAGE_DETAILS_Cork:INTERNAL=[/home/mick/dev/PyMesh/python/pymesh/third_party/include][/usr/lib/x86_64-linux-gnu/libcork.so][v()]

**Comment by ujikol** [comment]
Any idea? How shall I proceed?

**Comment by qnzhou** [comment]
You are linking with a cork library in the system folder.  Maybe you have install an older version of cork. 
 Can you set the environment variable `CORK_PATH` and recompile?  e.g.

```
export CORK_PATH=/home/mick/dev/PyMesh/python/pymesh/third_party/
```

**Comment by ujikol** [comment]
I tried it, and again:
ImportError: /home/mick/dev/PyMesh/python/pymesh/lib/libPyMesh-Boolean.so: undefined symbol: _Z17computeDifference11CorkTriMeshS_PS_

grep -i cork CMakeCache.txt
CORK_INCLUDE_DIRS:PATH=/home/mick/dev/PyMesh/python/pymesh/third_party/include
CORK_LIBRARIES:FILEPATH=/usr/lib/x86_64-linux-gnu/libcork.so
//ADVANCED property for variable: CORK_INCLUDE_DIRS
CORK_INCLUDE_DIRS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CORK_LIBRARIES
CORK_LIBRARIES-ADVANCED:INTERNAL=1
//Details about finding Cork
FIND_PACKAGE_MESSAGE_DETAILS_Cork:INTERNAL=[/home/mick/dev/PyMesh/python/pymesh/third_party/include][/usr/lib/x86_64-linux-gnu/libcork.so][v()]

So still include path = third_pary and lib path system installed.

**Comment by ujikol** [comment]
libcork and some other libs are .a instead of .so in third_party

**Comment by ujikol** [comment]
I did a pull, rm -rf build, rm -rf third_parties/build 3 days ago.

**Comment by yifita** [comment]
I have the same problem. were you able to solve it?

**Comment by yifita** [comment]
`grep -i cork CmakeCache.txt` returns the following.
I see I'm using the system cork library, maybe that's the issue?

```
CORK_INCLUDE_DIRS:PATH=/home/ywang/Documents/points/PyMesh/python/pymesh/third_party/include
CORK_LIBRARIES:FILEPATH=/usr/lib/x86_64-linux-gnu/libcork.so
//Enable Cork support
PYMESH_USE_CORK:BOOL=ON
//ADVANCED property for variable: CORK_INCLUDE_DIRS
CORK_INCLUDE_DIRS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CORK_LIBRARIES
CORK_LIBRARIES-ADVANCED:INTERNAL=1
//Details about finding Cork
FIND_PACKAGE_MESSAGE_DETAILS_Cork:INTERNAL=[/home/ywang/Documents/points/PyMesh/python/pymesh/third_party/include][/usr/lib/x86_64-linux-gnu/libcork.so][/usr/include/x86_64-linux-gnu][/usr/lib/x86_64-linux-gnu/libgmp.so][v()]
```

**Comment by yifita** [comment]
yes i confirm, after removing the ubuntu distribution it worked.

```
sudo apt remove libcork16 libcork-dev
cd $PYMESH/build
rm CMakeCache.txt
cmake ..
make -j
```
