### ISSUE TITLE
Failure in remove_degenerated_triangles_raw

### ISSUE THREAD

**Issue by dstoutamire** [qnzhou/PyMesh#114]
I occasionally see failures such as:

    499620: -97.2295  33.8188     -8.5
    499619: -97.2295  33.8188     -8.5
    499621: -97.2295  33.8188     -8.5
    |v0 - v1| = 3.69482e-13
    |v1 - v2| = 3.69482e-13
    |v2 - v0| = 0
    Traceback (most recent call last):
    ...
      File "/usr/local/lib/python3.6/dist-packages/pymesh/outerhull.py", line 70, in compute_outer_hull
        result = extract_layer(0);
      File "/usr/local/lib/python3.6/dist-packages/pymesh/outerhull.py", line 59, in extract_layer
        o_vertices, o_faces);
      File "/usr/local/lib/python3.6/dist-packages/pymesh/meshutils/remove_degenerated_triangles.py", line 29, in remove_degenerated_triangles_raw
        remover.run(num_iterations);
    RuntimeError: Triangle contains an zero edge, report this bug

The relevant code in `tools/MeshUtils/DegeneratedTriangleRemoval.cpp` says:

    // If the execution reached there, two of the vertices must have the same
    // coordinates, which should have been removed prior to calling this mehtod.

I suspect the problem is this typo: I replaced `remove_isolated_vertices_raw` with `remove_duplicated_vertices_raw` in `python/pymesh/outerhull.py`, and now everything runs fine for me.

Unfortunately the only test case I have is huge  (100MB+) and proprietary.

**Comment by qnzhou** [comment]
This is a bit concerning.  The suggestion for adding `remove_duplicated_vertices_raw` to `outerhull.py` is a valid walk around for now.  However, as your print out suggested, a zero edge survived my call to `remove_zero_edges()`.  This sounds like a bug.  I will look into it.

**Comment by scharlach** [comment]
i second this one. the same traceback, the same workaround helped. pymesh version 0.2.1

```
import pymesh

mesh = pymesh.meshio.load_mesh("buildings_42.obj")
# (mesh, info) = pymesh.remove_duplicated_vertices(mesh, 0.001)
# (mesh, info) = pymesh.collapse_short_edges(mesh, 0.001)
reduced = pymesh.compute_outer_hull(mesh)
```

an attempted fix with the middle two lines had no effect.
the input file: [buildings_42.obj.zip](https://github.com/PyMesh/PyMesh/files/4261977/buildings_42.obj.zip)

**Comment by bensums** [comment]
:+1: Same error here. Also ~100MB proprietary mesh
```
$ docker run -it --rm -v `pwd`:/models pymesh/pymesh fix_mesh.py /models/mesh.obj /models/mesh-fixed.obj
Target resolution: 0.011447073452078264 mm
11930: 0.742191  1.65863 0.111299
12076: 0.742191  1.65863 0.111299
12077: 0.732783  1.65726 0.115204
|v0 - v1| = 0
|v1 - v2| = 0.0102777
|v2 - v0| = 0.0102777
Traceback (most recent call last):
  File "/usr/local/bin/fix_mesh.py", line 113, in <module>
    main()
  File "/usr/local/bin/fix_mesh.py", line 104, in main
    mesh = fix_mesh(mesh, detail=args.detail)
  File "/usr/local/bin/fix_mesh.py", line 26, in fix_mesh
    mesh, __ = pymesh.remove_degenerated_triangles(mesh, 100)
  File "/usr/local/lib/python3.6/site-packages/pymesh/meshutils/remove_degenerated_triangles.py", line 48, in remove_degenerated_triangles
    mesh.vertices, mesh.faces, num_iterations)
  File "/usr/local/lib/python3.6/site-packages/pymesh/meshutils/remove_degenerated_triangles.py", line 29, in remove_degenerated_triangles_raw
    remover.run(num_iterations)
RuntimeError: Triangle contains an zero edge, report this bug
```

**Comment by hrehfeld** [comment]
This also seems to happen on this mesh 
[Mesh432.zip](https://github.com/PyMesh/PyMesh/files/6416000/Mesh432.zip)

from the bitterli staircase in pbrt format https://benedikt-bitterli.me/resources/pbrt-v3/staircase.zip
