### ISSUE TITLE
ERROR: Failure: ImportError (cannot import name SparseSolver)

### ISSUE THREAD

**Issue by grpaulfr** [qnzhou/PyMesh#15]
Running `python -c "import pymesh; pymesh.test()"` returns:

```
Running unit tests for pymesh
NumPy version 1.11.2
NumPy relaxed strides checking option: False
NumPy is installed in /home/grpaul/.pyenv/versions/2.7.11/lib/python2.7/site-packages/numpy
Python version 2.7.11 (default, Oct 25 2016, 09:45:51) [GCC 4.9.2]
nose version 1.3.7
......................................................................................................................E....
======================================================================
ERROR: Failure: ImportError (cannot import name SparseSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grpaul/.pyenv/versions/2.7.11/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/grpaul/.pyenv/versions/2.7.11/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/grpaul/.pyenv/versions/2.7.11/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/grpaul/.pyenv/versions/2.7.11/lib/python2.7/site-packages/pymesh-0.1-py2.7.egg/pymesh/tests/test_solver.py", line 1, in <module>
    from pymesh import SparseSolver
ImportError: cannot import name SparseSolver

----------------------------------------------------------------------
Ran 123 tests in 2.358s

FAILED (errors=1)
```

After checking you have `python/pymesh/Solver.py` where a class `SparseSolver` is defined. The problem is that it imports `PySparseSolver` which is not defined.

**Comment by qnzhou** [comment]
I have updated the code to comment out sparse solver tests, which is still not stable.  Could you `git pull` and test again?  Thanks!

**Comment by grpaulfr** [comment]
All tests passed:
```
Python version 2.7.11 (default, Oct 25 2016, 09:45:51) [GCC 4.9.2]
nose version 1.3.7
..........................................................................................................................
----------------------------------------------------------------------
Ran 122 tests in 2.361s

OK
```
