### ISSUE TITLE
libMesh.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by heitzmann** [qnzhou/PyMesh#30]
After compiling and installing pymesh, I get this error when importing pymesh.
The file is installed in `/usr/lib/python3.6/site-packages/pymesh/lib`, but it seems that the interpreter doesn't find it there.
Am I missing something obvious?

I'm on Archlinux  4.9.11, swig 3.0.12, python 3.6

The install script I'm using is https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pymesh-git
I don't compile the tools because tools_tests fail, and I also remove all scripts because I only need the main module, but I don't believe either have anything to do with this error.

**Comment by heitzmann** [comment]
Just an update: the problem has to do with absolute paths...
I don't usually use cmake, so I'm a bit lost on how to fix this. Any help appreciated.

**Comment by qnzhou** [comment]
Could you run `ls /usr/lib/python3.6/site-packages/pymesh/lib` to see if both `_PyMesh.so` and `libMesh.so` are both there?  If both exists, what does `ldd /usr/lib/python3.6/site-packages/pymesh/lib/_PyMesh.so | grep -i mesh` say?

I noticed that you config with the following command:

```
cmake .. \
	-DCMAKE_CXX_FLAGS='-w' \
	-DCMAKE_INSTALL_PREFIX="/usr" \
	-DCMAKE_SKIP_BUILD_RPATH=TRUE \
	-DCMAKE_SKIP_RPATH=TRUE
```

I suspect disabling rpath may cause the problem.  Maybe remove the flags related to rpath?

**Comment by heitzmann** [comment]
Thanks for the reply, @qnzhou.

I've tried that plus many other settings. It seems the libraries reference the absolute path where they were built.
Arch's `makepkg` builds everything in a user owned temporary directory and then moves everything to the correct place system-wide (`/usr` in this case), but the libraries have references to the original temporary directory (at least that what `grep` tells me).

I see that `setup.py` overides `cmake`, so I'm not sure any of the flags I use have the expected effect.

But what I guess is causing most of the problems is `SetInstallRpath.py` using absolute paths instead of relative ones.

**Comment by heitzmann** [comment]
Just a follow up: the current [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pymesh-git) mostly works (I'm having trouble finding CGAL, but that's another issue).

The problem here was that `SetInstallRpath.py` uses a `pymesh-XXX-pyXXX.egg` directory, which is not used in my system (I don't know if this is due to linux/setuptools versions or what).
I'll close the issue since I've found a workaround, but I'd suggest finding a more portable way to set `RPATH` if at all possible.

Thanks for the great work on putting PyMesh together!

**Comment by qnzhou** [comment]
Thanks for looking into this!  Python packaging is unfortunately confusing and inconsistent.  I am open for suggestions.  :)

**Comment by Mimickal** [comment]
I'm still seeing this issue with pymesh2 version 0.1.14. I installed via `pip3 install pymesh2`, which successfully downloaded and built the project. I cannot import the library without seeing this error though:
```
>>> import pymesh                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                            
  File "/home/mia/.local/lib/python3.7/site-packages/pymesh/swig/PyMesh.py", line 14, in swig_import_helper                                                                                   
    return importlib.import_module(mname)                                                                                                                                                     
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module                                                                                                                 
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                               
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                                                                                             
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                                           
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                                                                                                  
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked                                                                                                                           
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec                                                                                                                         
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module                                                                                                                  
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                                                
ImportError: libMesh.so: cannot open shared object file: No such file or directory
```
