### ISSUE TITLE
I have Important problem in using PyMesh

### ISSUE THREAD

**Issue by Igniscode** [qnzhou/PyMesh#34]
I'm using python 2.7 in windows by personal Reason.
Then I wanna use 'pymesh' library for some works.
but although the 'pymesh' module is already installed by using 
    
`python setup.py install`

, the python show me this error message

> 
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "E:\ProgramData\Anaconda2\lib\site-packages\pymesh-0.1-py2.7.egg\pymesh\__init__.py", line 18, in <module>
> from .Mesh import Mesh
> File "E:\ProgramData\Anaconda2\lib\site-packages\pymesh-0.1-py2.7.egg\pymesh\Mesh.py", line 5, in <module>
> import PyMesh
> importError: No module named PyMesh
> 

and because I thought that the reason of this error is I didn't build 'pymesh', I entered this code in CMD

` python setup.py build`

but the prompt also show me error message

> running build
> Overriding default build process
> error: [Error 2]

so ... in this case , how can i fix this simple problem
Plz help me ... T-T

+  I changed name of pymesh to PyMesh , then now it want be given PyMeshUtils

**Comment by arpit15** [comment]
@Igniscode Did you find any solution to your problem? Kindly do share the solution if you were able to solve it.

**Comment by mistamun** [comment]
I built all dependencies and built both pymesh and all tools and didn't spot any errors until the actually import pymesh in python3 which shows the same "No module name PyMesh" error.

Not sure if this is why I had to build everything locally as I don't have root access to the machine but it shouldn't make a difference...

**Comment by qnzhou** [comment]
Do you have multiple versions of python install on your computer?  In particular, what are the outputs if you `grep PYTHON_EXECUTABLE build/CMakeCache.txt` and `grep PTYHON_LIBRARIES build/CMakeCache.txt`?

**Comment by mistamun** [comment]
Yes, and that can indeed be a tricky problem but in this case I traced it back to a version of cmake which was too old.
