### ISSUE TITLE
Installation error during cmake stage for 3rd party libs (Ubuntu 14.04)

### ISSUE THREAD

**Issue by danielnflam** [qnzhou/PyMesh#39]
The first CMake error I encounter is:
-------------------
CMake Error in cgal/Installation/src/CGAL/CMakeLists.txt:
  Cannot find source file:

    INTERFACE

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: CGAL
CMake Error in cgal/Installation/src/CGAL/CMakeLists.txt:
  Exporting the target "CGAL" is not allowed since its linker language cannot
  be determined
-------------------------

I am wondering what I've done wrong?  I have installed CGAL from tarball, and it is sitting in my home directory.

**Comment by andreykurenkov** [comment]
Hey,
I had the same problem as you. This "INTERFACE" option was only added in cmake 3.0, and when I updated my cmake (which was 2.8) this worked fine. Here's one way to upgrade: https://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04

**Comment by qnzhou** [comment]
Thanks @andreykurenkov, I will update the `CMakeLists.txt` to require cmake 3.x.

I just tested the entire compilation on a clean slate Ubuntu 16.04, here are my steps:

```
apt-get update
apt-get install python3 libpython3-dev virtualenv git cmake swig gcc g++ libeigen3-dev libgmp-dev libmpfr-dev libboost-thread-dev libboost-dev
virtualenv --python=python3 ~/tmp
source ~/tmp/bin/activate
git clone https://github.com/qnzhou/PyMesh.git
cd PyMesh/
pip install -r python/requirements.txt 
git submodule init
git submodule update
cd third_party/
mkdir build
cd build/
cmake ..
make -j 2
make install
cd ../../
mkdir build
cd build/
cmake ..
make -j 2
make -j 2 tools
cd ..
./setup.py install --user
```

**Comment by danielnflam** [comment]
Thanks!  The installation and making happened fine, but when I ran the test:
make tools_tests

At the triangulation test stage, I got:

../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `omp_set_lock'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `omp_get_thread_num'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `omp_get_num_threads'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `GOMP_parallel'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `omp_init_lock'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `GOMP_loop_end_nowait'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `omp_unset_lock'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `omp_destroy_lock'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `GOMP_loop_dynamic_next'
../../../../python/pymesh/lib/libtriangulation.so: undefined reference to `GOMP_loop_dynamic_start'
collect2: error: ld returned 1 exit status
make[3]: *** [../bin/triangulation_tests] Error 1
make[2]: *** [tests/tools/Triangulation/CMakeFiles/triangulation_tests.dir/all] Error 2
make[1]: *** [tests/tools/CMakeFiles/tools_tests.dir/rule] Error 2
make: *** [tools_tests] Error 2

**Comment by danielnflam** [comment]
I ran the recommended python tests as well:
The output was:
ERROR: Failure: ImportError (cannot import name 'retriangulate')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/admindlam/.local/lib/python3.5/site-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/tests/test_triangulate.py", line 3, in <module>
    from pymesh import triangulate, retriangulate
ImportError: cannot import name 'retriangulate'

**Comment by danielnflam** [comment]
I copied your method, having given up on anaconda:

ERROR: Failure: ImportError (/home/admindlam/PyMesh/python/pymesh/lib/libtriangulation.so: undefined symbol: omp_set_lock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/admindlam/py3/lib/python3.4/site-packages/pymesh2-0.1.14-py3.4-linux-x86_64.egg/pymesh/swig/PyTriangulation.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_PyTriangulation', [dirname(__file__)])
  File "/home/admindlam/py3/lib/python3.4/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_PyTriangulation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admindlam/py3/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/admindlam/py3/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/admindlam/py3/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/admindlam/py3/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/admindlam/py3/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/admindlam/py3/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/admindlam/py3/lib/python3.4/site-packages/pymesh2-0.1.14-py3.4-linux-x86_64.egg/pymesh/tests/test_triangulate.py", line 3, in <module>
    from pymesh import triangulate, retriangulate
  File "/home/admindlam/py3/lib/python3.4/site-packages/pymesh2-0.1.14-py3.4-linux-x86_64.egg/pymesh/triangulate.py", line 2, in <module>
    import PyTriangulation
  File "/home/admindlam/py3/lib/python3.4/site-packages/pymesh2-0.1.14-py3.4-linux-x86_64.egg/pymesh/swig/PyTriangulation.py", line 28, in <module>
    _PyTriangulation = swig_import_helper()
  File "/home/admindlam/py3/lib/python3.4/site-packages/pymesh2-0.1.14-py3.4-linux-x86_64.egg/pymesh/swig/PyTriangulation.py", line 20, in swig_import_helper
    import _PyTriangulation
ImportError: /home/admindlam/PyMesh/python/pymesh/lib/libtriangulation.so: undefined symbol: omp_set_lock

----------------------------------------------------------------------
Ran 115 tests in 2.218s

FAILED (errors=4)

**Comment by danielnflam** [comment]
Just wondering; if you type "python -c "import sys ; print(sys.version)", is your python compiled from GCC 4.8.x ?  I suspect that may be one reason why my tests are failing.

**Comment by qnzhou** [comment]
It seems the problem is that `tools/triangulation` requires OpenMP on your setup, but the library is not compiled with OpenMP.  Can you change line 9 in `Settings.cmake` from
```
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```
to
```
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -openmp")
```
and see if it fixed the problem?  Thanks!

**Comment by danielnflam** [comment]
Thanks, it worked!  
I seem to be failing the wire tests now, however -- (it worked last time, though.)
I won't be using the wire functions, so I hope that they are independent of any other function in the library?
`
(Wire Test results from python test:)
python -c "import pymesh ; pymesh.test()"
Running unit tests for pymesh
NumPy version 1.10.4
NumPy relaxed strides checking option: False
NumPy is installed in /home/admindlam/py352/lib/python3.5/site-packages/numpy
Python version 3.5.2 (default, Apr 26 2017, 12:38:46) [GCC 6.2.0 20160901]
nose version 1.3.7
............................................EEE......................................................................
======================================================================
ERROR: Failure: ImportError (No module named 'WireTestCase')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/admindlam/py352/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/admindlam/py352/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/admindlam/py352/lib/python3.5/site-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/wires/tests/test_inflator.py", line 6, in <module>
    from WireTestCase import WireTestCase
ImportError: No module named 'WireTestCase'

======================================================================
ERROR: Failure: ImportError (No module named 'WireTestCase')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/admindlam/py352/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/admindlam/py352/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/admindlam/py352/lib/python3.5/site-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/wires/tests/test_tiler.py", line 7, in <module>
    from WireTestCase import WireTestCase
ImportError: No module named 'WireTestCase'

======================================================================
ERROR: Failure: ImportError (No module named 'WireTestCase')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/admindlam/py352/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/admindlam/py352/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/admindlam/py352/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/admindlam/py352/lib/python3.5/site-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/wires/tests/test_wire_network.py", line 5, in <module>
    from WireTestCase import WireTestCase
ImportError: No module named 'WireTestCase'

----------------------------------------------------------------------
Ran 117 tests in 2.353s

FAILED (errors=3)
`

**Comment by danielnflam** [comment]
Sorry, I fixed that too; it seems like there was a problem with my python build.  I reinstalled python, it works!
