### ISSUE TITLE
PyMesh test error: retriangulation (Ubuntu 14.04)

### ISSUE THREAD

**Issue by danielnflam** [qnzhou/PyMesh#40]
Just want to know if anyone has solved this problem I am having with the pymesh.test() check:

Running unit tests for pymesh
NumPy version 1.11.3
NumPy relaxed strides checking option: False
NumPy is installed in /home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/numpy
Python version 3.5.2 |Intel Corporation| (default, Feb  5 2017, 09:07:18) [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
nose version 1.3.7
...........................................................................................................................E.
======================================================================
ERROR: Failure: ImportError (cannot import name 'retriangulate')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/admindlam/anaconda2-7/envs/intelpy352/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/admindlam/.local/lib/python3.5/site-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/tests/test_triangulate.py", line 3, in <module>
    from pymesh import triangulate, retriangulate
ImportError: cannot import name 'retriangulate'

----------------------------------------------------------------------
Ran 125 tests in 6.407s

FAILED (errors=1)

**Comment by danielnflam** [comment]
Please close this, I have fixed it myself; it seems like a dodgy Python build on my end.
