### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by qqluckiest** [qnzhou/PyMesh#42]
Hello Mr. Zhou, 

can you please help me with the problem:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/swig/PyMesh.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit__PyMesh)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/local/lib/python3.5/dist-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
  File "/usr/local/lib/python3.5/dist-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/swig/PyMesh.py", line 17, in <module>
    _PyMesh = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/pymesh2-0.1.14-py3.5-linux-x86_64.egg/pymesh/swig/PyMesh.py", line 16, in swig_import_helper
    return importlib.import_module('_PyMesh')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dynamic module does not define module export function (PyInit__PyMesh)

There was no problem with my installation and i just doubt whether i make mistake with swig.

Thank you very much.

HM

**Comment by qqluckiest** [comment]
I suppose that would be a swig problem. And looking for a way to solve ist

**Comment by qqluckiest** [comment]
Hey, i've solved this Problem by changing all of the CMakeList.txt, in which the path to python and Numpy must be pointed out. 
Just Add 
`SET(PYTHON_INCLUDE_DIRS /usr/include/python3.5)`
`SET(PYTHON_EXECUTABLE /usr/bin/python3.5)`
`SET(NUMPY_INCLUDE_DIRS  /usr/include/python3.5/numpy)`
By doing so, there war no Need to set the python library path.
