### ISSUE TITLE
RuntimeError: Boolean engine "igl" is not supported.

### ISSUE THREAD

**Issue by ocni-dtu** [qnzhou/PyMesh#45]
After installing when I run:
python -c "import pymesh; pymesh.test()"
I get errors saying that "Boolean engine "igl" is not supported."
I have inserted some of the error messages blow.
I have tried to check for igl and i get:

Unix@DESKTOP-CAS28DH:~/PyMesh/build$ grep -i libigl CMakeCache.txt
LIBIGL_INCLUDE_DIRS:PATH=/home/Unix/PyMesh/third_party/libigl/include
//Details about finding LIBIGL
FIND_PACKAGE_MESSAGE_DETAILS_LIBIGL:INTERNAL=[/home/Unix/PyMesh/third_party/libigl/include][v()]
//ADVANCED property for variable: LIBIGL_INCLUDE_DIRS
LIBIGL_INCLUDE_DIRS-ADVANCED:INTERNAL=1

======================================================================
ERROR: test_no_intersection (test_selfintersection.SelfIntersectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/selfintersection.py", line 70, in detect_self_intersection
    import PyCGAL
ModuleNotFoundError: No module named 'PyCGAL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/tests/test_selfintersection.py", line 55, in test_no_intersection
    intersecting_faces = detect_self_intersection(mesh);
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/selfintersection.py", line 73, in detect_self_intersection
    "Self intersection detection is not supported");
NotImplementedError: Self intersection detection is not supported

======================================================================
ERROR: test_diag_box (test_slice_Mesh.SliceMeshTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/tests/test_slice_Mesh.py", line 33, in test_diag_box
    slices = slice_mesh(mesh, [1, 1, 1], N);
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/slice_mesh.py", line 53, in slice_mesh
    slabs = boolean(boxes, mesh, "intersection");
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/boolean.py", line 73, in boolean
    engine = PyBoolean.BooleanEngine.create(engine);
RuntimeError: Boolean engine "igl" is not supported.

======================================================================
ERROR: test_cube (test_winding_number.WindingNumberTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/tests/test_winding_number.py", line 21, in test_cube
    winding_numbers = compute_winding_number(mesh, queries);
  File "/home/Unix/.local/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/winding_number.py", line 10, in compute_winding_number
    engine = PyWindingNumber.WindingNumberEngine.create(engine);
RuntimeError: Unknown winding number engine: igl

----------------------------------------------------------------------
Ran 112 tests in 1.482s

FAILED (errors=48)

**Comment by qnzhou** [comment]
The `libigl` boolean module requires CGAL.  Can you check CGAL is found by PyMesh?

```
grep -i cgal CMakeCache.txt
```

**Comment by ocni-dtu** [comment]
Got following message:
Unix@DESKTOP-CAS28DH:~/PyMesh/build$ grep -i cgal CMakeCache.txt
//The directory containing CGALConfig.cmake. This is either the
// binary directory where CGAL was configured or PREFIX/lib/CGAL
CGAL_DIR:PATH=CGAL_DIR-NOTFOUND
//Disable CGAL from overwriting my cmake flags
CGAL_DONT_OVERRIDE_CMAKE_FLAGS:BOOL=TRUE

CGAL is installed. How do I set the CGAL dir?

**Comment by qnzhou** [comment]
hmmm, I have recently make CGAL available via submodule.  The cmake script should be able to find CGAL if you installed all the `third_party` libraries.

If you want to use pre-installed CGAL, you can set the environment variable `CGAL_PATH` that points to the directory containing the file `UseCGAL.cmake`.

**Comment by ocni-dtu** [comment]
I got the CGAL issues fixed and installed it all, but when I run:
python -c "import pymesh; pymesh.test()"
I get the following:

Running unit tests for pymesh
NumPy version 1.11.3
NumPy relaxed strides checking option: False
NumPy is installed in /home/Unix/anaconda3/lib/python3.6/site-packages/numpy
Python version 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
............................................OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
Afbrudt (SIGABRT) (smed kerne)
