### ISSUE TITLE
Failure to run tests

### ISSUE THREAD

**Issue by alecjacobson** [qnzhou/PyMesh#47]
I tried to install on a brand new MacBook Pro using home-brew and pip. Everything seemed to install and compile OK but the test command

```
python -c "import pymesh; pymesh.test()"
```
Produced a set of import errors:

```
Running unit tests for pymesh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/nosetester.py", line 374, in test
    self._show_system_info()
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/nosetester.py", line 227, in _show_system_info
    nose = import_nose()
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 70, in import_nose
    raise ImportError(msg)
ImportError: Need nose >= 1.0.0 for tests - see http://nose.readthedocs.io

```

**Comment by alecjacobson** [comment]
Ah. Apparently `pip install nose` is required to run this test. Perhaps this should be mentioned in the readme.

**Comment by qnzhou** [comment]
fixed in https://github.com/qnzhou/PyMesh/commit/68153df7ff7bb75172db194e907eb297411607d5
