### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by hiemstar** [qnzhou/PyMesh#51]
I successfully installed PyMesh using the system Python 2.7. All tests work. However, when I attempt
to install PyMesh as a package within Anaconda I get the following error upon running the tests:

python -c "import pymesh; pymesh.test()"
Fatal Python error: PyThreadState_Get: no current thread

Any ideas on how to make this work?

**Comment by hiemstar** [comment]
Before I used Anaconda with a python version 3.6 and got the error
python -c "import pymesh; pymesh.test()"
Fatal Python error: PyThreadState_Get: no current thread

If I use Anaconda with a python version 2.7 then I get the following error,

PyMesh (master) > python -c "import pymesh; pymesh.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rene/anaconda/lib/python2.7/site-packages/pymesh2-0.1.14-py2.7-macosx-10.7-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/Users/rene/anaconda/lib/python2.7/site-packages/pymesh2-0.1.14-py2.7-macosx-10.7-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
  File "/Users/rene/anaconda/lib/python2.7/site-packages/pymesh2-0.1.14-py2.7-macosx-10.7-x86_64.egg/pymesh/swig/PyMesh.py", line 28, in <module>
    _PyMesh = swig_import_helper()
  File "/Users/rene/anaconda/lib/python2.7/site-packages/pymesh2-0.1.14-py2.7-macosx-10.7-x86_64.egg/pymesh/swig/PyMesh.py", line 20, in swig_import_helper
    import _PyMesh
ImportError: dynamic module does not define init function (init_PyMesh)

**Comment by jjcao** [comment]
I have multiple python on a Ubuntu. When I build pymesh in a conda environment with python 2.7, cmake insists to use python 3.6 of another conda environment. How could I change this?

**Comment by jjcao** [comment]
Finally, I compiled PyMesh in a conda env with python 2.7.
Follow the installation steps, and make two changes.
1. change cmake to the following line when building the main project: 
> cmake -Wno-dev -DPYTHON_INCLUDE_DIR=/home/jack/miniconda3/envs/py27/include -DPYTHON_LIBRARY=/home/jack/miniconda3/envs/py27/lib/libpython2.7.so -DPYTHON_EXECUTABLE=/home/jack/miniconda3/envs/py27/bin/python2.7 ..

2. Before calling ./setup.py build, change a line in setup.py from 
> command = "cmake .. -DCMAKE_BUILD_TYPE=Release ...

to 

> command = "cmake .. -DCMAKE_BUILD_TYPE=Release -DPythonLibsNew_FIND_VERSION=2.7";
