### ISSUE TITLE
ImportError: No module named PyMesh

### ISSUE THREAD

**Issue by apal90** [qnzhou/PyMesh#90]
I have tried installing pymesh on both Mac OS and Windows, by downloading the source and installing using python setup.py install (as described in https://github.com/qnzhou/PyMesh).

In both cases, when I then ran the test code: `python -c "import pymesh; pymesh.test()"`, I get an `ImportError`. E.g., in Windows, I get the following traceback:

```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Program Files\Anaconda2\lib\site-packages\pymesh2-0.1.14-py2.7-win-amd64.egg\pymesh\__init__.py", line 18, in <module>
from .Mesh import Mesh
File "C:\Program Files\Anaconda2\lib\site-packages\pymesh2-0.1.14-py2.7-win-amd64.egg\pymesh\Mesh.py", line 5, in <module>
import PyMesh
ImportError: No module named PyMesh

```

Can someone please help?

**Comment by MadScientist356** [comment]
I am having the same issue. I think it is because the scripts that are called in __init__.py to be imported all say "import PyMesh". The capitalized name might be an issue. I tried editing the first file that is imported (Mesh.py) to say import pymesh for the import line, and tried it again. This time the most recent call that threw the error was from meshio.py which is the second file that is imported in __init__.py. I think to fix this all files that are called in __init__.py would have to switch from import PyMesh to import pymesh...there might also be something else that you can fix to accept the capitalized PyMesh as a valid call. I don't know how to fix that though, would wait for dev to respond.

**Comment by qnzhou** [comment]
Sorry about the delay.  I think this error is due to different python versions are used for building and running pymesh.  Can you check the following variables?

```
$ cd $PYMESH_PATH/build
$ grep PYTHON_EXECUTABLE CMakeCache.txt
$ grep PYTHON_LIBRARY CMakeCache.txt
```

**Comment by apal90** [comment]
Running

cd $PYMESH_PATH/build

just gives me

/build: No such file or directory.


Does that mean that nothing is installed? Or some other reason that
$PYMESH_PATH does not exist? I have a request -- could you possibly make it
so that pymesh can be installed via pip?

2018-06-03 20:30 GMT-05:00 Qingnan Zhou <notifications@github.com>:

**Comment by dfsp-spirit** [comment]
@apal90 In the documentation you linked, it says 

> Let $PYMESH_PATH be the root directory of the repository

So set that manually to the directory into which you cloned the git repo.

**Comment by apal90** [comment]
@dfsp-spirit OK, I go to `$PYMESH_PATH/build`, but now I get the error: `grep: CMakeCache.txt: No such file or directory`. What do I do?

**Comment by soheilysf** [comment]
I am having the same issue on Ubuntu 16. I tried installing the package by both running setup.py and CMake and every time I got the same error saying "No module named PyMesh"
for some reasons the PyMesh.py file that is imported in Mesh.py file is not being created during install.
Any luck?

**Comment by cloudliu01** [comment]
Here is what I did to resolve the issue:
####################################################
# Install PyMesh
https://pymesh.readthedocs.io/en/latest/installation.html#download-the-source
git clone https://github.com/PyMesh/PyMesh.git
cd PyMesh
git submodule update --init
export PYMESH_PATH=`pwd`
#update cmake (Please make sure to use 3.10.0 or higher version)
https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu
Download cmake 3.10.0
./configure
make 
sudo make install
cd $PYMESH_PATH
make
make tests
./setup.py install
`

**Comment by seanek2017** [comment]
Hi - I'm getting this problem but the solution doesn't work for me. When I try 

./configure

I get the error message

./configure: No such file or directory

Can you help please?

**Comment by Atokulus** [comment]
Hi there

I also encountered the same problem. I actually failed to also run `make` inside the `$PYMESH_PATH/build` folder (not just the `$PYMESH_PATH/third_party/build` one).

Best regards
@atokulus

**Comment by HaominIsMe** [comment]
> @apal90 In the documentation you linked, it says
> 
> > Let $PYMESH_PATH be the root directory of the repository
> 
> So set that manually to the directory into which you cloned the git repo.

Hi there,

I also encountered the same problem. 

here is what I got to run

`grep PYTHON_EXECUTABLE CMakeCache.txt`
PYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python3.6
//ADVANCED property for variable: PYTHON_EXECUTABLE
PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1
`grep PYTHON_LIBRARY CMakeCache.txt`
PYTHON_LIBRARY:FILEPATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
//ADVANCED property for variable: PYTHON_LIBRARY
PYTHON_LIBRARY-ADVANCED:INTERNAL=1

Do you have any idea on it?

Thanks,
Haomin

**Comment by CobaltGray** [comment]
I had the same problem. I think it is caused by conflicts between the different python libraries and paths on OSX. I fixed it by uninstalling and reinstalling a fresh version of anaconda. Then I rebuilt PyMesh and it all compiled and installed ok with tests passed.

**Comment by roaasoloh** [comment]
Pymesh was working correctly suddenly after some updating it gives:

> Traceback (most recent call last):
>   File "/home/roaa/anaconda3/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/swig/PyMesh.py", line 14, in swig_import_helper
>     return importlib.import_module(mname)
>   File "/home/roaa/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named '_PyMesh'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/roaa/anaconda3/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
>     from .Mesh import Mesh
>   File "/home/roaa/anaconda3/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
>     import PyMesh
>   File "/home/roaa/anaconda3/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/swig/PyMesh.py", line 17, in <module>
>     _PyMesh = swig_import_helper()
>   File "/home/roaa/anaconda3/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/swig/PyMesh.py", line 16, in swig_import_helper
>     return importlib.import_module('_PyMesh')
>   File "/home/roaa/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named '_PyMesh'

**Comment by fabj191** [comment]
Hi everyone, encountering the same problem here. Trying to install with the 'setup.py install' command. This is on Windows 10 (64-bit), Python 3.7.4 (also 64-bit). 

Installation is reported to be successful, the build is created and pip recognises pymesh2 as installed (not pymesh, though!). But when I run the test, I get the same "No module named PyMesh" when it tries to call that module in the Mesh.py file (see error message below). Interestingly I get this not only when running the test, but when I generally want to import pymesh.  

I've tried the suggestions in this thread that (I understood to) refer to Windows. Made sure that this is the only Python installation on my system (including  registry and PATH). The CMakeCache.txt is not being generated (or at least I can't find it).

Would be grateful for any advice. Thanks!

Error message:

_PS D:\PyMesh-master> python -c "import pymesh; pymesh.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\pymesh2-0.2.1-py3.7-win-amd64.egg\pymesh\__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "C:\Program Files\Python37\lib\site-packages\pymesh2-0.2.1-py3.7-win-amd64.egg\pymesh\Mesh.py", line 5, in <module>
    import PyMesh
ModuleNotFoundError: No module named 'PyMesh'_

**Comment by CH1111** [comment]
I have met the same problem. And I think it's due to different python versions  used for building and installing pymesh.  Beacuse I found I build the code with python 3.7 but install it with python 2.7 automatically. And when I use python 3.7 intsall it again, the problem is gone

**Comment by piango** [comment]
Has anyone found a solution to all these errors reported here. I have been trying all solutions that I can find in forums and still can't seem to get it to work.
I have these errors:
1. can't find ./configure to work
2. make command is not found
3. cmake way of building pymesh doesn't work.

i feel that there is one step that needs to work to make all work. but i am really stuck. 

I am using windows

**Comment by kintoresenpai** [comment]
Hello, everybody. I've installed PyMesh in Ubuntu. I'm kinda new in this SO, so I've had hard times to install it. But, it worked. 

First: Put "sudo" before every command. 
The tutorial is based on (minimally changed)  https://pymesh.readthedocs.io/en/latest/installation.html 

So, here we go:

1)Open a terminal, and run the following commands:

sudo git clone https://github.com/PyMesh/PyMesh.git
cd PyMesh
git submodule update --init
export PYMESH_PATH=`pwd`

Now:

sudo apt-get install \
    libeigen3-dev \
    libgmp-dev \
    libgmpxx4ldbl \
    libmpfr-dev \
    libboost-dev \
    libboost-thread-dev \
    libtbb-dev \
    python3-dev

Then:

sudo -H pip install -r $PYMESH_PATH/python/requirements.txt

Finally:

sudo ./setup.py build

sudo ./setup.py install

**Comment by hanamizukigakki** [comment]
> > @apal90 In the documentation you linked, it says
> > > Let $PYMESH_PATH be the root directory of the repository
> > 
> > 
> > So set that manually to the directory into which you cloned the git repo.
> 
> Hi there,
> 
> I also encountered the same problem.
> 
> here is what I got to run
> 
> `grep PYTHON_EXECUTABLE CMakeCache.txt`
> PYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python3.6
> //ADVANCED property for variable: PYTHON_EXECUTABLE
> PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1
> `grep PYTHON_LIBRARY CMakeCache.txt`
> PYTHON_LIBRARY:FILEPATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
> //ADVANCED property for variable: PYTHON_LIBRARY
> PYTHON_LIBRARY-ADVANCED:INTERNAL=1
> 
> Do you have any idea on it?
> 
> Thanks,
> Haomin

Same problem, any solutions?

**Comment by evastgh** [comment]
I had almost the same issue and tried calling the setup.py with python3 instead of calling it directly. 
```
python3 setup.py build
python3 setup.py install
```
It installed PyMesh with Python3 and things now work for me. (on a Mac)

**Comment by wesleyfox** [comment]
I managed to make it work. I will post the procedure I adopted. I use **Debian 9.13**. So I believe it will serve for s.o debian like. I also apologize for my google translator english

I did the following steps.

1. **Optional** - Set the python version as the system default. I chose to do it because I have other versions of python on my system.

**Comment by wesleyfox** [comment]
I managed to make it work. I will post the procedure I adopted. I use **Debian 9.13**.  
I believe it will works for debian likes. I also apologize for my google translator english

### I did the following steps to install PyMesh

**Optional** - Set the python version as the system default. I chose to do it because I have other versions of python on my system.
`# update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
`


**1. Installing dependencies**
_Here I used administrator permission for installation via apt-get._
`# apt install libeigen3-dev libgmp-dev libgmpxx4ldbl libmpfr-dev libboost-dev libboost-thread-dev libtbb-dev python3-dev curl git -y`
_Pip installation_
`# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py`


**2. clone, part of third parties and requirements**
_As a common user of the system._
``$  git clone https://github.com/PyMesh/PyMesh.git ``
``$ cd PyMesh ``
``$ git submodule update --init ``
``$ export PYMESH_PATH=`pwd` ``
``$ pip install -r $PYMESH_PATH/python/requirements.txt``

**3. Install CMAKE**
_When getting errors in the build step, I noticed that the messages pointed to my outdated version of CMAKE. I upgraded **(version 3.13.4)** using the Debian Buster repository. You may prefer to build from sources. I chose to use apt-get._ 
`# echo "deb http://deb.debian.org/debian buster main" >> /etc/apt/sources.list.d/buster.list`
`# apt update && apt install cmake -y`

**4. Build and install** 
_Still in the PyMesh directory, with a common user._
`$ ./setup.py build`
`$ ./setup.py install  --user `

**5. Test**
`$ python -c "import pymesh; pymesh.test()"`

reference links
https://pymesh.readthedocs.io/en/latest/
https://github.com/PyMesh/PyMesh
https://linuxconfig.org/how-to-change-default-python-version-on-debian-9-stretch-linux
https://pip.pypa.io/en/stable/installing/

Hope this helps.

**Comment by chetanjain2099** [comment]
> > > @apal90 In the documentation you linked, it says
> > > > Let $PYMESH_PATH be the root directory of the repository
> > > 
> > > 
> > > So set that manually to the directory into which you cloned the git repo.
> > 
> > 
> > Hi there,
> > I also encountered the same problem.
> > here is what I got to run
> > `grep PYTHON_EXECUTABLE CMakeCache.txt`
> > PYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python3.6
> > //ADVANCED property for variable: PYTHON_EXECUTABLE
> > PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1
> > `grep PYTHON_LIBRARY CMakeCache.txt`
> > PYTHON_LIBRARY:FILEPATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
> > //ADVANCED property for variable: PYTHON_LIBRARY
> > PYTHON_LIBRARY-ADVANCED:INTERNAL=1
> > Do you have any idea on it?
> > Thanks,
> > Haomin
> 
> Same problem, any solutions?

Has anybody solved this issue? 

I was able to successfully install PyMesh in Python 3.7 and Python 3.8 but in both of them I am getting import PyMesh error. 

`ImportError: DLL load failed: The specified module could not be found.`

**Comment by GiantRoot** [comment]
Duplicate of #141

I didn't try but I think this is  the solution. https://github.com/PyMesh/PyMesh/issues/141#issuecomment-461423571

**Comment by shadhanu** [comment]
I was having the same issue in MacOS when I had python 3.9

Below commands did the trick. Remember to use pip3 with python 3.*

pip3 install numpy
pip3 install nose
pip3 install scipy

Then ran the test as
pymesh.test() - all good!

---------------------------
Running unit tests for pymesh
NumPy version 1.22.2
NumPy relaxed strides checking option: True
NumPy is installed in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy
Python version 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 17:02:14) [Clang 6.0 (clang-600.0.57)]
nose version 1.3.7
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nose/plugins/attrib.py:242: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  if isinstance(value, collections.Callable):
............................................................................./Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymesh2-0.3-py3.9-macosx-10.9-x86_64.egg/pymesh/misc/quaternion.py:16: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self.__quat = np.array(quat, dtype=np.float)
.............................Warning: Complex edge loop detected!  Vertex 0 has valance 3

Warning: Complex edge loop detected!  Vertex 0 has valance 3

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py:525: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  warnings.warn("TestResult has no addExpectedFailure method, reporting as passes",

.............................................................S......S

----------------------------------------------------------------------

Ran 175 tests in 3.313s

OK (SKIP=2)

**Comment by andrewyguo** [comment]
had this issue on Ubuntu 20.04. Was able to solve this by following the **Build with CMake**[ instructions here](https://pymesh.readthedocs.io/en/latest/installation.html#build-with-cmake).
