### ISSUE TITLE
Building on Manjaro Linux (Arch Linux) fails

### ISSUE THREAD

**Issue by BjoernLange** [qnzhou/PyMesh#99]
I'm running Manjaro Linux (an Arch Linux based distribution) on my PC and try to build PyMesh from source using the steps in the [installation guide](http://pymesh.readthedocs.io/en/latest/installation.html#download-the-source). Unfortunately the build processes crashes with the following error message:
```
Traceback (most recent call last):
  File "setup.py", line 178, in <module>
    distclass=BinaryDistribution,
  File "/home/bjoern/Applications/Anaconda/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/bjoern/Applications/Anaconda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/bjoern/Applications/Anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/bjoern/Applications/Anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 88, in run
    self.build_pymesh();
  File "setup.py", line 83, in build_pymesh
    check_call(command.split());
  File "/home/bjoern/Applications/Anaconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
```
(note about the line numbers: because my system seems not to have enough memory to build using all cores I needed to limit the amount of cores to 4, thus all line numbers from the stack trace above are increased by 1)

This seems to be caused by a compiler error:
```
Scanning dependencies of target lib_Tetrahedralization
[ 66%] Building CXX object tools/Tetrahedralization/CMakeFiles/lib_Tetrahedralization.dir/TetrahedralizationEngine.cpp.o
In file included from /home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/internal/boost/mutable_queue.hpp:27,
                 from /home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/Modifiable_priority_queue.h:27,
                 from /home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/Mesh_3/Sliver_perturber.h:70,
                 from /home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/perturb_mesh_3.h:34,
                 from /home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/optimize_mesh_3.h:31,
                 from /home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/refine_mesh_3.h:36,
                 from /home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/make_mesh_3.h:32,
                 from /home/bjoern/PyMesh/tools/Tetrahedralization/CGAL/CGALMeshGen.h:8,
                 from /home/bjoern/PyMesh/tools/Tetrahedralization/TetrahedralizationEngine.cpp:13:
/home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/internal/boost/array_binary_tree.hpp:54:28: Fehler: expected template-name before »<« token
         : ::boost::iterator<std::forward_iterator_tag,
                            ^
/home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/internal/boost/array_binary_tree.hpp:54:28: Fehler: expected »{« before »<« token
/home/bjoern/PyMesh/python/pymesh/third_party/include/CGAL/internal/boost/array_binary_tree.hpp:54:28: Fehler: expected unqualified-id before »<« token
```
This is followed by tons of other errors.

The full error trace can be found here: [log_short.txt](https://github.com/qnzhou/PyMesh/files/2188012/log_short.txt)
The full log of the installation can be found here: [log_full.txt](https://github.com/qnzhou/PyMesh/files/2188015/log_full.txt)

As a quick solution it would be enough to be able to disable lib_Tetrahedralization as I'm not using any of its features. Thanks for your help!

**Comment by qnzhou** [comment]
I think you are hitting this problem: https://svn.boost.org/trac10/ticket/13505

One way to fix it is to use lower version boost.  boost @1.66.0_3 seems compile fine.  Another way will be upgrading CGAL (the only dependency that uses boost).

**Comment by BjoernLange** [comment]
Thanks for your help!

After downgrading from boost 1.67 to 1.66 the build and all tests finish smoothly.

**Comment by qnzhou** [comment]
Great!  I am closing this issue.
